# Assignment : NumPy  by Tanuja Dasari

----------------------------------------------------------------------------------------

# NumPy Arrays

- **Printing Basic Array**

In [2]:
   import numpy as td
   arr1=td.array([0,4,0,6,2,0,0,1])
   arr2=td.array(['T','a','n','u','j','a','D','a','s','a','r','i'])
   arr3= td.array((0, 4, 0, 6, 2,0,0,1)) 
   print(arr1)
   print(arr2)
   print(arr3)
   print(type(arr1))

[0 4 0 6 2 0 0 1]
['T' 'a' 'n' 'u' 'j' 'a' 'D' 'a' 's' 'a' 'r' 'i']
[0 4 0 6 2 0 0 1]
<class 'numpy.ndarray'>


- **Arrays using np.zeros(), np.ones(), np.arange()**

In [3]:
   import numpy as td
   a=td.zeros(9)
   b=td.ones(9)
   c=td.arange(9)
   d=td.arange(0,9) 
   e=td.arange(0,9,1)
   print(a)
   print(b)
   print(c)
   print(d)
   print(e)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8]


## N Dimensional Arrays

- **2D Array(2 Dimensional Array) and Checking the number of dimensions using  "ndim"**

In [4]:
   import numpy as td
   arr1=td.array([[9,18,27],[36,45,54]])
   arr2=td.array([[9,18,27],[27,9,18],[18,27,9]])
   arr3=td.array([['T','a','n','u','j','a'],['d','a','s','a','r','i']])
   zeros=td.zeros((9,9))
   ones=td.ones((4,4),dtype='int64')  
   arr4= td.array(94)
   arr5= td.array([16, 12, 1999, 7, 9])
   arr6 = td.array([[[9, 18, 27], [9, 27, 729]], [[729, 9, 27], [27, 729, 9]]])
   print(arr1)
   print("\n",arr2)
   print("\n",arr3)
   print("\n",zeros)
   print("\n",ones)
   print("\n",arr1.ndim)
   print("\n",arr2.ndim)
   print("\n",arr3.ndim)
   print("\n",arr4.ndim) 
   print("\n",arr5.ndim)
   print("\n",arr6.ndim) 
   print("\n",zeros.ndim) 

[[ 9 18 27]
 [36 45 54]]

 [[ 9 18 27]
 [27  9 18]
 [18 27  9]]

 [['T' 'a' 'n' 'u' 'j' 'a']
 ['d' 'a' 's' 'a' 'r' 'i']]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

 2

 2

 2

 0

 1

 3

 2


## Basic Arithematic operations using Arrays

In [28]:
   import numpy as ds
   arr1=ds.array([9,9,9,9])
   arr2=ds.array([7,7,7,7])
   x=arr1+arr2
   y=arr1-arr2
   z=arr1/arr2
   w= arr1*arr2
   print("arr1:",arr1)
   print("arr2:",arr2)
   print("Addition:",x)
   print("Subtraction:",y)
   print("Division:",y) 
   print("Multiplication:",w) 
   print("Addition of \"1\":",x+1)
   print("Subtracting of \"1\":",y-1)

arr1: [9 9 9 9]
arr2: [7 7 7 7]
Addition: [16 16 16 16]
Subtraction: [2 2 2 2]
Division: [2 2 2 2]
Multiplication: [63 63 63 63]
Addition of "1": [17 17 17 17]
Subtracting of "1": [1 1 1 1]


## Array Indexing

In [32]:
   import numpy as ds
   arr1= ds.array([3,2,3,4])
   arr2= ds.array([2,1,1,3])
   arr3= ds.array(['D','u','r','g','a','S','a','i'])
   arr4= ds.array([[9,18,27,36,45], [54,63,72,81,90]])
   print(arr1[2]) 
   print(arr1[-1]) 
   print(arr2[1])
   print(arr3[0]) 
   print(arr4[1][3]) 
   print(arr4[1,4]) 

3
4
1
D
81
90


## Array Slicing 

In [37]:
   import numpy as ds
   arr1=ds.array(['D','u','r','g','a','S','a','i'])
   arr2=ds.array([9,7,18,14,27,21,36,28,45])
   arr3=ds.array([[9, 18, 27, 36, 45], [7, 14, 21, 28, 36]])
   
   print(arr1[:5])
   print(arr1[0:5])
   print(arr1[5:])
   print(arr1[::2])   
   print(arr2[-4:-1])
   print(arr2[::2])
   print(arr3[1,1:4])
   print(arr3[0:2, 2])
   print(arr3[0:2, 1:4])

['D' 'u' 'r' 'g' 'a']
['D' 'u' 'r' 'g' 'a']
['S' 'a' 'i']
['D' 'r' 'a' 'a']
[21 36 28]
[ 9 18 27 36 45]
[14 21 28]
[27 21]
[[18 27 36]
 [14 21 28]]


# NumPy Functions

## Array Shape
- **Array shape along with size and dimensions**

In [41]:
   import numpy as ds
   arr1 = ds.array([[9, 18, 27, 36], [45, 54, 63, 72]])
   arr2= ds.array([9,99,999,9999])

   print("shape of arr1:",arr1.shape)
   print("shape of arr2:",arr2.shape)
   print("size of arr2:",arr2.size)
   print("dimensions of arr2:",arr2.ndim)

shape of arr1: (2, 4)
shape of arr2: (4,)
size of arr2: 4
dimensions of arr2: 1


## Array Reshape
- **Reshape from 1-Dimensional to 2-Dimensional**

In [10]:
   import numpy as np
   arr1 = np.array([9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99, 0])
   newarr1 = arr1.reshape(4, 3)
   arr2 = np.array(['T','a','n','u','j','a','D','a','s'])
   newarr2 = arr2.reshape(3,3)
   print(newarr1)
   print("\n",newarr2)

[[ 9 18 27]
 [36 45 54]
 [63 72 81]
 [90 99  0]]

 [['T' 'a' 'n']
 ['u' 'j' 'a']
 ['D' 'a' 's']]


- **Reshape from 1-Dimensional to 3-Dimensional**

In [9]:
   import numpy as td
   arr = td.array([9, 90, 0, 81, 18, 27, 72, 63, 36, 54, 45, 99])
   newarr = arr.reshape(2, 3, 2)
   print(newarr)

[[[ 9 90]
  [ 0 81]
  [18 27]]

 [[72 63]
  [36 54]
  [45 99]]]


- **Multi-Dimensional Array into 1-Dimensional Array**

In [8]:
   import numpy as td
   arr = td.array([[10, 20, 30], [40, 50, 60]])
   newarr = arr.reshape(-1)
   print(newarr)

[10 20 30 40 50 60]


## Sorting
- **Using where()**

In [7]:
   import numpy as td
   arr1 = td.array([9, 16, 21, 24, 25, 36, 42])
   a = td.where(arr1 == 4)
   b = td.where(arr1%2 == 0)
   c = td.where(arr1%2 == 1)
   print(a)
   print(b)
   print(c)

(array([], dtype=int64),)
(array([1, 3, 5, 6], dtype=int64),)
(array([0, 2, 4], dtype=int64),)


## Searching
- Using **searchsorted()**

In [6]:
   import numpy as td
   arr1 = td.array([36, 49, 64, 81])
   a = td.searchsorted(arr1, 49)
   print(a)
   arr2 = ds.array([11, 33, 55, 77])
   b = td.searchsorted(arr2, [22, 44, 66])
   print(b)

1
[1 2 3]


## Mean Median Mode & Standard Deviation (σ)

In [5]:
  import numpy as td
  from scipy import stats
  data = [99,90,81,72,108,81,63,54,99,81,90,45,81]
  x = td.mean(data) 
  y = td.median(data)
  z = stats.mode(data)
  s = td.std(data)
  print("Mean:",x)
  print("Median:",y)  
  print("Mode:",z)
  print("Standard Deviation:",s)
    


Mean: 80.3076923076923
Median: 81.0
Mode: ModeResult(mode=array([81]), count=array([4]))
Standard Deviation: 17.459335679425603
